let mapleader=" "
syntax on
set showcmd
set number
set cursorline
set wildmenu 
set hlsearch
exec "nohlsearch"
set incsearch
set ignorecase
set smartcase
set scrolloff=5
set clipboard=unnamed

let g:netrw_winsize=25
let g:netrw_liststyle=3

noremap <LEADER>v <C-Q>
noremap <LEADER><CR> :nohlsearch<CR>
nnoremap <LEADER>e :Lex<cr>
nnoremap <LEADER>s :wincmd w<cr>

map <LEADER>l :set splitright<CR>:vsplit<CR>
map <LEADER>h :set nosplitright<CR>:vsplit<CR>
map <LEADER>k :set nosplitbelow<CR>:split<CR>
map <LEADER>j :set splitbelow<CR>:split<CR>

map <left> :vertical resize-5<CR>
map <right> :vertical resize+5<CR>

nnoremap J 5j<cr>
nnoremap K 5k<cr>
map s <nop>
map S :w<cr>
map Q :q<cr>
map R :source ~/.vim/vimrc<cr>

highlight Visual ctermbg=8
highlight search ctermbg=8
highlight LineNr ctermfg=6
highlight CursorLineNr ctermfg=5 ctermbg=0 cterm=NONE
highlight CursorLine ctermbg=0 cterm=NONE


call plug#begin()

" List your plugins here
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
call plug#end()
